# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "marimo",
#   "numpy",
#   "pandas",
#   "matplotlib",
#   "scikit-learn"
# ]
# ///

import marimo

__generated_with = "0.23.8"
app = marimo.App(width="medium")


@app.cell(hide_code=True)
def _():
    # These are the only packages used in the notebook.
    # marimo builds the app, numpy simulates arrays, pandas stores tables,
    # and matplotlib makes the plots.
    import marimo as mo
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    from sklearn.linear_model import LinearRegression, LogisticRegression

    return LinearRegression, mo, np, pd, plt


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # AIPW and double robustness

    **Goal.** Compare two badly misspecified plug-in estimators with their AIPW corrections when the propensity score model is correctly specified.

    The target parameter follows the notation from the slides:

    \[
    \psi = E(Y^1 - Y^0).
    \]

    The observed data are \(O=(W,A,Y)\), the outcome regression is
    \(Q(w,a)=E(Y\mid W=w,A=a)\), and the propensity score is
    \(\varpi(w)=\pi(1\mid w)=P(A=1\mid W=w)\).

    This lab is designed to be run as an app. Most code is hidden. Your task is to move the levers, run the estimators, and explain what happens.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Data-generating mechanism

    We generate \(W=(W_1,\ldots,W_5)\), then treatment, then the observed outcome \(Y=Y^A\).

    \[
    W_j\sim N(0,1),\qquad j=1,\ldots,5.
    \]

    Treatment assignment is confounded and can have weak overlap:

    \[
    \operatorname{logit}\{\varpi_{\lambda}(W)\}
    =\lambda\Big[-0.10
    +0.80W_1
    -0.90W_2
    +0.70W_3
    +0.70W_1W_2
    -0.60\mathbb{I}(W_4>0)
    +0.50\sin(W_5)\Big].
    \]

    Larger \(\lambda\) means **more lack of overlap**. When \(\lambda\) is large, some units have \(\varpi(W)\) close to 0 or 1.

    The potential outcomes are generated by

    \[
    Y^a=\mu_0(W;\rho)+a\tau(W;\rho)+\varepsilon,
    \qquad \varepsilon\sim N(0,1),
    \]

    where \(\rho\) controls the **misspecification pressure** faced by simple outcome regressions:

    \[
    \begin{aligned}
    \mu_0(W;\rho)
    &=1+
    \rho\Big\{1.80\sin(W_1)+1.30W_2^2-1.50W_3
    +1.10W_4W_5 \\
    &\hspace{2.7cm}+0.80\mathbb{I}(W_1>0)W_2-0.80\cos(W_5)\Big\},\\[0.4em]
    \tau(W;\rho)
    &=1+
    \rho\Big\{0.80W_1-0.70W_2+0.90\mathbb{I}(W_3>0)
    +0.60\sin(W_4) \\
    &\hspace{2.7cm}+0.50W_2W_5-0.40W_1W_4\Big\}.
    \end{aligned}
    \]

    Therefore, the true conditional treatment effect is \(\tau(W)=Y^1-Y^0\), and the target is \(\psi=\mathbb{E}\{\tau(W)\}\).
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## The two deliberately misspecified outcome regressions

    The lab fits two outcome models. Both are intentionally wrong, but in different ways.

    **Misspecified model 1: simple linear regression**

    \[
    Q_1^{\text{mis}}(w,a;\beta)
    =\beta_0+\beta_A a+\beta_1w_1+\beta_2w_2.
    \]

    This model omits \(W_3,W_4,W_5\), all nonlinear terms, all interactions, and all treatment-effect heterogeneity.

    **Misspecified model 2: partial interactions but missing important confounders**

    \[
    Q_2^{\text{mis}}(w,a;\beta)
    =\beta_0+\beta_Aa+\beta_1w_1+\beta_2w_2
    +\beta_{12}w_1w_2+\beta_{A1}aw_1+\beta_{A2}aw_2.
    \]

    This model looks more sophisticated, but it still omits the important confounder \(W_3\), the terms involving \(W_4,W_5\), the nonlinear terms \(\sin(W_1),W_2^2,\cos(W_5),\sin(W_4)\), and several treatment-effect modifiers.

    We compare four estimators:

    \[
    \widehat\psi_{\text{plug-in},1},\qquad
    \widehat\psi_{\text{plug-in},2},\qquad
    \widehat\psi_{\text{AIPW},1},\qquad
    \widehat\psi_{\text{AIPW},2}.
    \]

    For both AIPW estimators, \(\widehat\varpi(W)\) is set to the **correct propensity score from the simulator**, with a mild numerical truncation at 0.005 and 0.995. This isolates the double-robustness idea: even if \(Q\) is badly wrong, AIPW can still recover \(\psi\) when \(\varpi\) is correct and overlap is not too weak.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    lab_n = mo.ui.slider(
        start=500,
        stop=5000,
        step=250,
        value=3000,
        label="Sample size n",
    )
    lab_overlap = mo.ui.slider(
        start=0.25,
        stop=2.50,
        step=0.25,
        value=1.00,
        label="Lack of overlap λ: multiplier on logit{varpi(W)}",
    )
    lab_misspec = mo.ui.slider(
        start=0.00,
        stop=3.00,
        step=0.25,
        value=1.50,
        label="Misspecification of outcome regression ρ",
    )
    lab_seed = mo.ui.number(value=1, start=1, stop=99999, label="Random seed")
    lab_run_button = mo.ui.run_button(label="Run the four estimators")

    mo.vstack([
        mo.md(r"""
        ## Choose the experiment

        Use these three levers:

        1. **Sample size \(n\)**: larger samples reduce variance.
        2. **Lack of overlap \(\lambda\)**: larger values make \(\varpi(W)\) closer to 0 or 1 for some units.
        3. **Outcome misspecification \(\rho\)**: larger values make the true \(Q(w,a)\) more nonlinear and more unlike the two fitted outcome regressions.

        Suggested first run: \(n=3000\), \(\lambda=1.00\), \(\rho=1.50\), seed 1. Then increase \(\rho\) and \(\lambda\) separately.
        """),
        mo.hstack([lab_n, lab_overlap]),
        mo.hstack([lab_misspec, lab_seed]),
        lab_run_button,
    ])
    return lab_misspec, lab_n, lab_overlap, lab_run_button, lab_seed


@app.cell(hide_code=True)
def _(LinearRegression, np, pd, plt):
    def expit(x):
        return 1.0 / (1.0 + np.exp(-x))

    def generate_data(n, overlap_lambda=1.0, misspec_rho=1.5, seed=1):
        rng = np.random.default_rng(seed)
        W = rng.normal(size=(n, 5))
        W1, W2, W3, W4, W5 = W.T

        eta = overlap_lambda * (
            -0.10
            + 0.80 * W1
            - 0.90 * W2
            + 0.70 * W3
            + 0.70 * W1 * W2
            - 0.60 * (W4 > 0)
            + 0.50 * np.sin(W5)
        )
        varpi = expit(eta)
        A = rng.binomial(1, varpi)

        mu0 = 1.0 + misspec_rho * (
            1.80 * np.sin(W1)
            + 1.30 * W2**2
            - 1.50 * W3
            + 1.10 * W4 * W5
            + 0.80 * (W1 > 0) * W2
            - 0.80 * np.cos(W5)
        )
        tau = 1.0 + misspec_rho * (
            0.80 * W1
            - 0.70 * W2
            + 0.90 * (W3 > 0)
            + 0.60 * np.sin(W4)
            + 0.50 * W2 * W5
            - 0.40 * W1 * W4
        )
        eps = rng.normal(scale=1.0, size=n)
        Y_zero = mu0 + eps
        Y_one = mu0 + tau + eps
        Y = mu0 + A * tau + eps

        df = pd.DataFrame(W, columns=[f"W{j}" for j in range(1, 6)])
        df["A"] = A
        df["Y"] = Y
        df["Y_zero_true"] = Y_zero
        df["Y_one_true"] = Y_one
        df["tau_true"] = tau
        df["varpi_true"] = varpi
        return df

    def design_Q(df, a_value=None, q_model="Q1"):
        d = df.copy()
        if a_value is not None:
            d["A"] = a_value
        W1 = d["W1"].to_numpy()
        W2 = d["W2"].to_numpy()
        A = d["A"].to_numpy()
        if q_model == "Q1":
            return np.column_stack([A, W1, W2])
        if q_model == "Q2":
            return np.column_stack([A, W1, W2, W1 * W2, A * W1, A * W2])
        raise ValueError("q_model must be either 'Q1' or 'Q2'")

    def design_varpi(df):
        W1 = df["W1"].to_numpy()
        W2 = df["W2"].to_numpy()
        W3 = df["W3"].to_numpy()
        W4 = df["W4"].to_numpy()
        W5 = df["W5"].to_numpy()
        return np.column_stack([W1, W2, W3, W1 * W2, (W4 > 0), np.sin(W5)])

    def fit_Q_and_predict(df, q_model):
        model = LinearRegression()
        X = design_Q(df, q_model=q_model)
        y = df["Y"].to_numpy()
        model.fit(X, y)
        q1 = model.predict(design_Q(df, a_value=1, q_model=q_model))
        q0 = model.predict(design_Q(df, a_value=0, q_model=q_model))
        return q1, q0

    def plugin_estimate(df, q_model):
        q1, q0 = fit_Q_and_predict(df, q_model)
        return float(np.mean(q1 - q0))

    def fit_correct_varpi(df):
        # Pedagogical choice: use the correct propensity score from the simulator.
        # The truncation is only for numerical stability when the overlap lever is large.
        return np.clip(df["varpi_true"].to_numpy(), 0.005, 0.995)

    def aipw_estimate(df, q_model, varpi_hat):
        q1, q0 = fit_Q_and_predict(df, q_model)
        A = df["A"].to_numpy()
        Y = df["Y"].to_numpy()
        phi = q1 - q0 + A / varpi_hat * (Y - q1) - (1 - A) / (1 - varpi_hat) * (Y - q0)
        estimate = float(np.mean(phi))
        se = float(np.std(phi, ddof=1) / np.sqrt(len(df)))
        return estimate, se, phi

    def bootstrap_plugin_ci(df, q_model, B=60, seed=123):
        rng = np.random.default_rng(seed)
        n = len(df)
        estimates = []
        for _ in range(B):
            idx = rng.integers(0, n, size=n)
            boot = df.iloc[idx].reset_index(drop=True)
            estimates.append(plugin_estimate(boot, q_model))
        estimates = np.asarray(estimates)
        se = float(np.std(estimates, ddof=1))
        lo, hi = np.quantile(estimates, [0.025, 0.975])
        return se, float(lo), float(hi)

    def run_all_estimators(n, overlap_lambda, misspec_rho, seed):
        df = generate_data(
            int(n),
            overlap_lambda=float(overlap_lambda),
            misspec_rho=float(misspec_rho),
            seed=int(seed),
        )
        true_psi = float(np.mean(df["tau_true"]))
        varpi_hat = fit_correct_varpi(df)

        rows = []
        for label, q_model in [
            ("Plug-in 1: simple linear Q", "Q1"),
            ("Plug-in 2: partial interactions Q", "Q2"),
        ]:
            est = plugin_estimate(df, q_model)
            se, lo, hi = bootstrap_plugin_ci(df, q_model, B=60, seed=int(seed) + (11 if q_model == "Q1" else 29))
            rows.append({
                "estimator": label,
                "estimate": est,
                "SE": se,
                "CI lower": lo,
                "CI upper": hi,
                "bias": est - true_psi,
                "uncertainty": "small bootstrap",
            })

        for label, q_model in [
            ("AIPW 1: Q1 + correct varpi", "Q1"),
            ("AIPW 2: Q2 + correct varpi", "Q2"),
        ]:
            est, se, _ = aipw_estimate(df, q_model, varpi_hat)
            rows.append({
                "estimator": label,
                "estimate": est,
                "SE": se,
                "CI lower": est - 1.96 * se,
                "CI upper": est + 1.96 * se,
                "bias": est - true_psi,
                "uncertainty": "EIF SE",
            })

        results = pd.DataFrame(rows)
        varpi_summary = pd.DataFrame({
            "quantity": [
                "true psi",
                "treatment prevalence",
                "min true varpi(W)",
                "5% true varpi(W)",
                "median true varpi(W)",
                "95% true varpi(W)",
                "max true varpi(W)",
            ],
            "value": [
                true_psi,
                float(df["A"].mean()),
                float(df["varpi_true"].min()),
                float(df["varpi_true"].quantile(0.05)),
                float(df["varpi_true"].median()),
                float(df["varpi_true"].quantile(0.95)),
                float(df["varpi_true"].max()),
            ],
        })
        return df, results, varpi_summary, true_psi

    def make_ci_plot(results, true_psi):
        plot_df = results.copy()
        y = np.arange(len(plot_df))
        x = plot_df["estimate"].to_numpy()
        lo = plot_df["CI lower"].to_numpy()
        hi = plot_df["CI upper"].to_numpy()
        xerr = np.vstack([x - lo, hi - x])
        fig, ax = plt.subplots(figsize=(8.2, 4.8))
        ax.errorbar(x, y, xerr=xerr, fmt="o", capsize=4, linewidth=1.5)
        ax.axvline(true_psi, linestyle="--", linewidth=1.2)
        ax.set_yticks(y)
        ax.set_yticklabels(plot_df["estimator"])
        ax.set_xlabel("ATE estimate with 95% interval")
        ax.set_title("AIPW repairs misspecified Q when varpi is correct")
        ax.grid(axis="x", alpha=0.25)
        fig.tight_layout()
        return fig

    def diagnostic_message(results, overlap_lambda, misspec_rho):
        plugin_bias = results.loc[results["estimator"].str.startswith("Plug-in"), "bias"].abs().mean()
        aipw_bias = results.loc[results["estimator"].str.startswith("AIPW"), "bias"].abs().mean()
        lines = []
        lines.append(
            f"Average absolute plug-in bias: {plugin_bias:.3f}. Average absolute AIPW bias: {aipw_bias:.3f}."
        )
        if aipw_bias < plugin_bias:
            lines.append(
                "This is the intended double-robustness pattern: Q is badly misspecified, but the correctly specified propensity score model helps the AIPW estimator move toward ψ."
            )
        else:
            lines.append(
                "Here AIPW did not dominate the plug-ins in this one finite sample. Discuss variance, weak overlap, and finite-sample instability rather than treating double robustness as a deterministic finite-sample guarantee."
            )
        if float(overlap_lambda) >= 1.75:
            lines.append(
                "The overlap parameter is large. Some estimated weights can become large, so AIPW may have wider intervals and more finite-sample variability."
            )
        if float(misspec_rho) >= 2.25:
            lines.append(
                "The outcome regression is severely nonlinear. The two plug-ins are expected to be badly biased because their Q-models miss central parts of the true assignment mechanism."
            )
        return "\n\n".join(lines)

    return diagnostic_message, make_ci_plot, run_all_estimators


@app.cell(hide_code=True)
def _(
    lab_misspec,
    lab_n,
    lab_overlap,
    lab_run_button,
    lab_seed,
    mo,
    run_all_estimators,
):
    mo.stop(not lab_run_button.value, mo.md("Press **Run the four estimators** after selecting the three levers."))
    lab_df, lab_results, lab_varpi_summary, lab_true_psi = run_all_estimators(
        n=lab_n.value,
        overlap_lambda=lab_overlap.value,
        misspec_rho=lab_misspec.value,
        seed=lab_seed.value,
    )
    return lab_results, lab_true_psi, lab_varpi_summary


@app.cell(hide_code=True)
def _(
    diagnostic_message,
    lab_misspec,
    lab_overlap,
    lab_results,
    lab_true_psi,
    lab_varpi_summary,
    make_ci_plot,
    mo,
):
    fig = make_ci_plot(lab_results, lab_true_psi)
    display_results = lab_results.copy()
    display_results["covers true psi"] = (
        (display_results["CI lower"] <= lab_true_psi) &
        (lab_true_psi <= display_results["CI upper"])
    )
    mo.vstack([
        mo.md("## Results"),
        mo.md(r"The dashed vertical line in the plot is the finite-sample truth, \(n^{-1}\sum_i \tau(W_i)\)."),
        fig,
        display_results.round(3),
        mo.md("## Propensity-score and overlap diagnostics"),
        lab_varpi_summary.round(3),
        mo.md("## Diagnostic interpretation"),
        mo.md(diagnostic_message(lab_results, lab_overlap.value, lab_misspec.value)),
    ])
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Student discussion prompts

    1. **Increase outcome-model misspecification.** Raise \(\rho\) so that the fitted outcome regressions become increasingly misspecified. Which estimators change the most? Which ones are more stable, and why?

    2. **Create overlap problems.** Increase \(\lambda\) so that some units have very small or very large estimated propensity scores. What happens to the confidence intervals of the AIPW estimators? Relate this behavior to the inverse-propensity terms in the one-step correction:
    \[
    \frac{A}{\widehat\pi(1\mid W)}
    \qquad\text{and}\qquad
    \frac{1-A}{\widehat\pi(0\mid W)}
    \]
    3. **Compare the two misspecified outcome models.** Look at \(Q_1^{\mathrm{mis}}\) and \(Q_2^{\mathrm{mis}}\). What information is each model missing? What would a better outcome model need to include?

    4. **Discuss why AIPW is not automatic protection.** AIPW can correct some outcome-regression mistakes when the propensity score is well estimated, but what happens if \(\widehat\pi\) is also misspecified or if overlap is weak? Which diagnostics or plots would help you decide whether to trust a plug-in estimator, an AIPW estimator, or neither? Remember that in real data we do not observe the oracle curve shown as the dashed line.

    5. **Design your own stress test.** Try new combinations of \(\rho\), \(\lambda\), and the outcome-model choices. Can you find a setting where AIPW improves over plug-in? Can you find a setting where AIPW becomes unstable? What feature of the simulation explains each case?

    6. Feel free to try new configurations, to check the code, and to formulate questions.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Running this notebook

    From the directory containing this file:

    ```bash
    pip install marimo numpy pandas matplotlib
    marimo edit 3b_aipw_double_robustness_marimo.py
    ```

    To serve it as an app instead of opening the notebook editor:

    ```bash
    marimo run 3b_aipw_double_robustness_marimo.py
    ```
    """)
    return


if __name__ == "__main__":
    app.run()
