# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "marimo",
#   "numpy",
#   "pandas",
#   "matplotlib",
#   "scikit-learn"
# ]
# ///

import marimo

__generated_with = "0.23.8"
app = marimo.App(width="medium")


@app.cell(hide_code=True)
def _():
    # These are the only packages used in the notebook.
    # marimo builds the app, numpy simulates arrays, pandas stores tables,
    # and matplotlib makes the plots.
    import marimo as mo
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    from sklearn.linear_model import LinearRegression, LogisticRegression
    from sklearn.tree import DecisionTreeRegressor
    from sklearn.model_selection import KFold

    return (
        DecisionTreeRegressor,
        KFold,
        LinearRegression,
        LogisticRegression,
        mo,
        np,
        pd,
        plt,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # DML, TMLE, and why cross-fitting matters

    **Goal.** Compare a misspecified plug-in estimator, a naive AIPW estimator, DML, and TMLE for the ATE

    \[
    \psi = E(Y^1-Y^0).
    \]

    The observed data are \(O=(W,A,Y)\), the outcome regression is
    \(Q(w,a)=E(Y\mid W=w,A=a)\), and the propensity score is
    \(\varpi(w)=\pi(1\mid w)=P(A=1\mid W=w)\).

    The point of this lab is not to debug code. The point is to see one practical difference between **ordinary AIPW** and **DML**:

    \[
    \text{naive AIPW: fit nuisances and evaluate them on the same data,}
    \]

    while

    \[
    \text{DML: evaluate nuisance predictions out-of-fold using cross-fitting.}
    \]

    When the nuisance regression overfits, this difference becomes visible.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Data-generating mechanism

    We generate \(W=(W_1,\ldots,W_5)\), then treatment, then the observed outcome \(Y=Y^A\).

    \[
    W_j\sim N(0,1),\qquad j=1,\ldots,5.
    \]

    Treatment assignment is confounded:

    \[
    \operatorname{logit}\{\varpi_\lambda(W)\}
    =\lambda\Big[-0.10
    +0.80W_1
    -0.90W_2
    +0.70W_3
    +0.70W_1W_2
    -0.60\mathbb{I}(W_4>0)
    +0.50\sin(W_5)\Big].
    \]

    Larger \(\lambda\) means **more lack of overlap**.

    The potential outcomes are generated by

    \[
    Y^a=\mu_0(W)+a\tau(W)+\varepsilon,
    \qquad \varepsilon\sim N(0,1),
    \]

    where

    \[
    \begin{aligned}
    \mu_0(W)
    &=1+1.60\sin(W_1)+1.20W_2^2-1.20W_3
    +1.10W_4W_5 \\
    &\hspace{1.0cm}+0.80\mathbb{I}(W_1>0)W_2-0.70\cos(W_5),\\[0.4em]
    \tau(W)
    &=1+0.80W_1-0.70W_2+0.80\mathbb{I}(W_3>0)
    +0.60\sin(W_4) \\
    &\hspace{1.0cm}+0.50W_2W_5-0.40W_1W_4.
    \end{aligned}
    \]

    Therefore, the true conditional treatment effect is \(\tau(W)=Y^1-Y^0\), and the target is \(\psi=\mathbb{E}\{\tau(W)\}\).
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Estimators compared in this lab

    **1. Misspecified plug-in.** We intentionally fit the wrong outcome regression:

    \[
    Q^{\mathrm{mis}}(w,a;\beta)
    =\beta_0+\beta_Aa+\beta_1w_1+\beta_2w_2.
    \]

    This model omits \(W_3,W_4,W_5\), nonlinear terms, interactions, and all treatment-effect heterogeneity.

    **2. Naïve AIPW.** We fit a flexible regression tree for \(Q(w,a)\), but evaluate \(\widehat Q(W_i,A_i)\) on the **same observations used to train it**:

    \[
    \widehat\psi_{\mathrm{AIPW}}
    =n^{-1}\sum_{i=1}^n\left[
    \widehat Q(W_i,1)-\widehat Q(W_i,0)
    +\left(\frac{A_i}{\widehat{\pi}(1\mid W_i)}
    -\frac{1-A_i}{\widehat{\pi}(0\mid W_i)}\right)\{Y_i-\widehat Q(W_i,A_i)\}
    \right].
    \]

    **3. DML.** We use the same score, but \(\widehat Q(W_i,A_i)\) is computed out-of-fold. The observation \(i\) is not used to train its own nuisance prediction.

    **4. TMLE.** Starting from the same cross-fitted nuisance predictions as DML, we make a least-squares targeting update:

    \[
    \widehat Q^\star(W,A)=\widehat Q(W,A)+\widehat\epsilon H(W,A),
    \qquad
    H(W,A)=\frac{A}{\widehat{\pi}(1\mid W)}-\frac{1-A}{\widehat{\pi}(0\mid W)},
    \]

    with

    \[
    \widehat\epsilon
    =\frac{\sum_{i=1}^n\left[H(W_i,A_i)\{Y_i-\widehat Q(W_i,A_i)\}\right]}
    {\sum_{i=1}^n\{H(W_i,A_i)^2\}}.
    \]

    The propensity-score lever lets you compare two options. The first option uses the true \(\varpi(W)\) from the simulator, which isolates the effect of overfitting in \(Q\). The second option estimates a deliberately misspecified propensity score by fitting the logistic model

    \[
    \operatorname{logit}\{\varpi^{\mathrm{mis}}(W;\alpha)\}
    =\alpha_0+\alpha_1W_1+\alpha_2W_2+\alpha_{12}W_1W_2.
    \]

    This model ignores \(W_3,W_4,W_5\), even though those variables affect the true treatment assignment above. When this option is selected, every estimator that uses inverse-propensity weights uses this misspecified \(\widehat\varpi^{\mathrm{mis}}(W)\).
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    lab_n = mo.ui.slider(
        start=500,
        stop=5000,
        step=250,
        value=1500,
        label="Sample size n",
    )
    lab_overlap = mo.ui.slider(
        start=0.25,
        stop=2.00,
        step=0.25,
        value=1.00,
        label="Lack of overlap λ: multiplier on logit{varpi(W)}",
    )
    lab_overfit = mo.ui.slider(
        start=0.00,
        stop=1.00,
        step=0.10,
        value=1.00,
        label="Overfitting pressure κ for Q learner: 0 = smooth tree, 1 = very adaptive tree",
    )
    lab_propensity = mo.ui.dropdown(
        options=["true propensity scores", "misspecified propensity scores"],
        value="true propensity scores",
        label="Propensity score used by AIPW, DML, and TMLE",
    )
    lab_seed = mo.ui.number(value=1, start=1, stop=99999, label="Random seed")
    lab_run_button = mo.ui.run_button(label="Run DML/TMLE experiment")

    mo.vstack([
        mo.md(r"""
        ## Choose the experiment

        Use these four levers:

        1. **Sample size \(n\)**: larger samples reduce variance.
        2. **Lack of overlap \(\lambda\)**: larger values make \(\varpi(W)\) closer to 0 or 1 for some units.
        3. **Overfitting pressure \(\kappa\)**: larger values make the flexible \(Q\)-learner more adaptive.
        4. **Propensity score**: compare the true \(\varpi(W)\) against a misspecified logistic regression that ignores \(W_3,W_4,W_5\).

        Suggested first run: \(n=1500\), \(\lambda=1.00\), \(\kappa=1.00\), true propensity scores, seed 1.

        """),
        mo.hstack([lab_n, lab_overlap]),
        mo.hstack([lab_overfit, lab_propensity]),
        mo.hstack([lab_seed, lab_run_button]),
    ])
    return (
        lab_n,
        lab_overfit,
        lab_overlap,
        lab_propensity,
        lab_run_button,
        lab_seed,
    )


@app.cell(hide_code=True)
def _(
    DecisionTreeRegressor,
    KFold,
    LinearRegression,
    LogisticRegression,
    np,
    pd,
    plt,
):
    def expit(x):
        return 1.0 / (1.0 + np.exp(-x))

    def generate_data(n, overlap_lambda=1.0, seed=1):
        rng = np.random.default_rng(seed)
        W = rng.normal(size=(n, 5))
        W1, W2, W3, W4, W5 = W.T

        eta = overlap_lambda * (
            -0.10
            + 0.80 * W1
            - 0.90 * W2
            + 0.70 * W3
            + 0.70 * W1 * W2
            - 0.60 * (W4 > 0)
            + 0.50 * np.sin(W5)
        )
        varpi = expit(eta)
        A = rng.binomial(1, varpi)

        mu0 = (
            1.0
            + 1.60 * np.sin(W1)
            + 1.20 * W2**2
            - 1.20 * W3
            + 1.10 * W4 * W5
            + 0.80 * (W1 > 0) * W2
            - 0.70 * np.cos(W5)
        )
        tau = (
            1.0
            + 0.80 * W1
            - 0.70 * W2
            + 0.80 * (W3 > 0)
            + 0.60 * np.sin(W4)
            + 0.50 * W2 * W5
            - 0.40 * W1 * W4
        )
        eps = rng.normal(scale=1.0, size=n)
        Y_zero = mu0 + eps
        Y_one = mu0 + tau + eps
        Y = mu0 + A * tau + eps

        df = pd.DataFrame(W, columns=[f"W{j}" for j in range(1, 6)])
        df["A"] = A
        df["Y"] = Y
        df["Y_zero_true"] = Y_zero
        df["Y_one_true"] = Y_one
        df["tau_true"] = tau
        df["varpi_true"] = varpi
        return df

    def design_Q_tree(df, a_value=None):
        d = df.copy()
        if a_value is not None:
            d["A"] = a_value
        W1 = d["W1"].to_numpy()
        W2 = d["W2"].to_numpy()
        W3 = d["W3"].to_numpy()
        W4 = d["W4"].to_numpy()
        W5 = d["W5"].to_numpy()
        A = d["A"].to_numpy()
        return np.column_stack([
            A,
            W1,
            W2,
            W3,
            W4,
            W5,
            W1 * W2,
            W4 * W5,
            np.sin(W1),
            W2**2,
            np.sin(W4),
            np.cos(W5),
            A * W1,
            A * W2,
            A * (W3 > 0),
            A * np.sin(W4),
            A * W2 * W5,
            A * W1 * W4,
        ])

    def design_Q_plugin(df, a_value=None):
        d = df.copy()
        if a_value is not None:
            d["A"] = a_value
        return d[["A", "W1", "W2"]].to_numpy()

    def design_varpi_mis(df):
        W1 = df["W1"].to_numpy()
        W2 = df["W2"].to_numpy()
        return np.column_stack([W1, W2, W1 * W2])

    def fit_propensity(df, propensity_choice):
        if propensity_choice == "true propensity scores":
            varpi = df["varpi_true"].to_numpy()
        else:
            model = LogisticRegression(max_iter=2000, C=1e6)
            model.fit(design_varpi_mis(df), df["A"].to_numpy())
            varpi = model.predict_proba(design_varpi_mis(df))[:, 1]
        return np.clip(varpi, 0.01, 0.99)

    def min_leaf_from_kappa(kappa):
        # kappa = 0 is a smoother tree; kappa = 1 is an almost unregularized tree.
        return max(1, int(round(80 * (1.0 - float(kappa)) + 1 * float(kappa))))

    def phi_ate(df, q1, q0, qA, varpi):
        A = df["A"].to_numpy()
        Y = df["Y"].to_numpy()
        return q1 - q0 + A / varpi * (Y - qA) - (1 - A) / (1 - varpi) * (Y - qA)

    def fit_plugin_predictions(df):
        model = LinearRegression()
        model.fit(design_Q_plugin(df), df["Y"].to_numpy())
        q1 = model.predict(design_Q_plugin(df, a_value=1))
        q0 = model.predict(design_Q_plugin(df, a_value=0))
        return q1, q0

    def plugin_estimate(df):
        q1, q0 = fit_plugin_predictions(df)
        return float(np.mean(q1 - q0))

    def bootstrap_plugin_ci(df, B=60, seed=123):
        rng = np.random.default_rng(seed)
        n = len(df)
        estimates = []
        for _ in range(B):
            idx = rng.integers(0, n, size=n)
            boot = df.iloc[idx].reset_index(drop=True)
            estimates.append(plugin_estimate(boot))
        estimates = np.asarray(estimates)
        se = float(np.std(estimates, ddof=1))
        lo, hi = np.quantile(estimates, [0.025, 0.975])
        return se, float(lo), float(hi)

    def fit_tree_in_sample(df, kappa):
        leaf = min_leaf_from_kappa(kappa)
        model = DecisionTreeRegressor(min_samples_leaf=leaf, random_state=10)
        model.fit(design_Q_tree(df), df["Y"].to_numpy())
        q1 = model.predict(design_Q_tree(df, a_value=1))
        q0 = model.predict(design_Q_tree(df, a_value=0))
        qA = model.predict(design_Q_tree(df))
        return q1, q0, qA, leaf

    def fit_tree_crossfit(df, kappa, n_splits=3, seed=1):
        n = len(df)
        q1 = np.zeros(n)
        q0 = np.zeros(n)
        qA = np.zeros(n)
        leaf = min_leaf_from_kappa(kappa)
        kfold = KFold(n_splits=n_splits, shuffle=True, random_state=seed)
        for train, test in kfold.split(df):
            dtr = df.iloc[train]
            dte = df.iloc[test]
            model = DecisionTreeRegressor(min_samples_leaf=leaf, random_state=10)
            model.fit(design_Q_tree(dtr), dtr["Y"].to_numpy())
            q1[test] = model.predict(design_Q_tree(dte, a_value=1))
            q0[test] = model.predict(design_Q_tree(dte, a_value=0))
            qA[test] = model.predict(design_Q_tree(dte))
        return q1, q0, qA, leaf

    def tmle_least_squares_update(df, q1, q0, qA, varpi):
        A = df["A"].to_numpy()
        Y = df["Y"].to_numpy()
        H = A / varpi - (1 - A) / (1 - varpi)
        H1 = 1.0 / varpi
        H0 = -1.0 / (1.0 - varpi)
        epsilon = float(np.sum(H * (Y - qA)) / (np.sum(H**2) + 1e-8))
        q1_star = q1 + epsilon * H1
        q0_star = q0 + epsilon * H0
        qA_star = qA + epsilon * H
        return q1_star, q0_star, qA_star, epsilon

    def run_estimators(n, overlap_lambda, kappa, propensity_choice, seed):
        df = generate_data(int(n), overlap_lambda=float(overlap_lambda), seed=int(seed))
        true_psi = float(np.mean(df["tau_true"]))
        # The selected propensity score is used by every estimator with inverse-propensity weights.
        # Truncation only avoids numerical explosions in extreme overlap settings.
        varpi = fit_propensity(df, propensity_choice)

        rows = []

        plug = plugin_estimate(df)
        plug_se, plug_lo, plug_hi = bootstrap_plugin_ci(df, B=60, seed=int(seed) + 101)
        rows.append({
            "estimator": "Misspecified plug-in",
            "estimate": plug,
            "SE": plug_se,
            "CI lower": plug_lo,
            "CI upper": plug_hi,
            "bias": plug - true_psi,
            "uncertainty": "small bootstrap",
        })

        q1_in, q0_in, qA_in, leaf = fit_tree_in_sample(df, kappa)
        phi_in = phi_ate(df, q1_in, q0_in, qA_in, varpi)
        aipw = float(np.mean(phi_in))
        aipw_se = float(np.std(phi_in, ddof=1) / np.sqrt(len(df)))
        rows.append({
            "estimator": "Naive AIPW: in-sample Q",
            "estimate": aipw,
            "SE": aipw_se,
            "CI lower": aipw - 1.96 * aipw_se,
            "CI upper": aipw + 1.96 * aipw_se,
            "bias": aipw - true_psi,
            "uncertainty": "EIF SE",
        })

        q1_cf, q0_cf, qA_cf, _ = fit_tree_crossfit(df, kappa, n_splits=3, seed=int(seed) + 55)
        phi_cf = phi_ate(df, q1_cf, q0_cf, qA_cf, varpi)
        dml = float(np.mean(phi_cf))
        dml_se = float(np.std(phi_cf, ddof=1) / np.sqrt(len(df)))
        rows.append({
            "estimator": "DML: cross-fitted Q",
            "estimate": dml,
            "SE": dml_se,
            "CI lower": dml - 1.96 * dml_se,
            "CI upper": dml + 1.96 * dml_se,
            "bias": dml - true_psi,
            "uncertainty": "EIF SE",
        })

        q1_star, q0_star, qA_star, epsilon = tmle_least_squares_update(df, q1_cf, q0_cf, qA_cf, varpi)
        tmle = float(np.mean(q1_star - q0_star))
        phi_star = phi_ate(df, q1_star, q0_star, qA_star, varpi)
        tmle_se = float(np.std(phi_star, ddof=1) / np.sqrt(len(df)))
        rows.append({
            "estimator": "TMLE: targeted cross-fitted Q",
            "estimate": tmle,
            "SE": tmle_se,
            "CI lower": tmle - 1.96 * tmle_se,
            "CI upper": tmle + 1.96 * tmle_se,
            "bias": tmle - true_psi,
            "uncertainty": "EIF SE after targeting",
        })

        results = pd.DataFrame(rows)
        results["covers true psi"] = (results["CI lower"] <= true_psi) & (true_psi <= results["CI upper"])

        q_plugin_in = float(np.mean(q1_in - q0_in))
        q_plugin_cf = float(np.mean(q1_cf - q0_cf))
        residual_in = float(np.mean(np.abs(df["Y"].to_numpy() - qA_in)))
        residual_cf = float(np.mean(np.abs(df["Y"].to_numpy() - qA_cf)))
        diagnostic = pd.DataFrame({
            "quantity": [
                "true psi",
                "tree min_samples_leaf",
                "treatment prevalence",
                "propensity misspecified? (1=yes)",
                "mean absolute error of selected varpi",
                "5% true varpi(W)",
                "median true varpi(W)",
                "95% true varpi(W)",
                "5% selected varpi(W)",
                "median selected varpi(W)",
                "95% selected varpi(W)",
                "mean |Y - Q_hat(W,A)|, in-sample",
                "mean |Y - Q_hat(W,A)|, out-of-fold",
                "naive AIPW correction relative to its ML plug-in",
                "DML correction relative to its ML plug-in",
                "TMLE epsilon",
                "mean EIF after TMLE targeting",
            ],
            "value": [
                true_psi,
                leaf,
                float(df["A"].mean()),
                float(propensity_choice == "misspecified propensity scores"),
                float(np.mean(np.abs(varpi - np.clip(df["varpi_true"].to_numpy(), 0.01, 0.99)))),
                float(np.quantile(df["varpi_true"], 0.05)),
                float(np.median(df["varpi_true"])),
                float(np.quantile(df["varpi_true"], 0.95)),
                float(np.quantile(varpi, 0.05)),
                float(np.median(varpi)),
                float(np.quantile(varpi, 0.95)),
                residual_in,
                residual_cf,
                aipw - q_plugin_in,
                dml - q_plugin_cf,
                epsilon,
                float(np.mean(phi_star - tmle)),
            ],
        })
        return df, results, diagnostic, true_psi

    def make_ci_plot(results, true_psi):
        plot_df = results.copy()
        y = np.arange(len(plot_df))
        x = plot_df["estimate"].to_numpy()
        lo = plot_df["CI lower"].to_numpy()
        hi = plot_df["CI upper"].to_numpy()
        xerr = np.vstack([x - lo, hi - x])

        fig, ax = plt.subplots(figsize=(8.4, 4.8))
        ax.errorbar(x, y, xerr=xerr, fmt="o", capsize=4, linewidth=1.5)
        ax.axvline(true_psi, linestyle="--", linewidth=1.2)
        ax.set_yticks(y)
        ax.set_yticklabels(plot_df["estimator"])
        ax.set_xlabel("ATE estimate with 95% interval")
        ax.set_title("DML/TMLE use out-of-fold residuals; naive AIPW may overfit")
        ax.grid(axis="x", alpha=0.25)
        fig.tight_layout()
        return fig

    def diagnostic_message(results, diagnostic, kappa, overlap_lambda, propensity_choice):
        d = dict(zip(diagnostic["quantity"], diagnostic["value"]))
        naive_bias = abs(float(results.loc[results["estimator"] == "Naive AIPW: in-sample Q", "bias"].iloc[0]))
        dml_bias = abs(float(results.loc[results["estimator"] == "DML: cross-fitted Q", "bias"].iloc[0]))
        tmle_bias = abs(float(results.loc[results["estimator"] == "TMLE: targeted cross-fitted Q", "bias"].iloc[0]))
        lines = []
        lines.append(
            f"The in-sample residual size is {d['mean |Y - Q_hat(W,A)|, in-sample']:.3f}, while the out-of-fold residual size is {d['mean |Y - Q_hat(W,A)|, out-of-fold']:.3f}."
        )
        if propensity_choice == "misspecified propensity scores":
            lines.append(
                f"The propensity score is misspecified: the selected model ignores W3, W4, and W5. The mean absolute difference from the true truncated varpi(W) is {d['mean absolute error of selected varpi']:.3f}. AIPW, DML, and TMLE all use these wrong inverse-propensity weights."
            )
        else:
            lines.append(
                "The propensity score is the true varpi(W) from the simulator, so the comparison mainly isolates overfitting in Q and the role of cross-fitting."
            )
        if float(kappa) >= 0.8:
            lines.append(
                "High κ makes the Q-learner very adaptive. The naive AIPW correction can become too small because Q_hat(W_i,A_i) was trained on Y_i itself. DML avoids this by using out-of-fold nuisance predictions."
            )
        else:
            lines.append(
                "With lower κ, the Q-learner is smoother. Naive AIPW and DML should become more similar because the own-observation overfitting problem is weaker."
            )
        if dml_bias < naive_bias:
            lines.append(
                "Here DML improved over naive AIPW. This is the intended cross-fitting lesson: the formula is similar, but the nuisance-prediction protocol matters."
            )
        else:
            lines.append(
                "In this finite sample, DML did not dominate naive AIPW. Try another seed or increase κ. The important diagnostic is whether in-sample residuals are artificially small."
            )
        if tmle_bias <= dml_bias + 0.05:
            lines.append(
                "TMLE is close to DML, as expected: both are based on the same orthogonal score. TMLE differs by updating Q so that the empirical EIF is approximately zero."
            )
        if float(overlap_lambda) >= 1.5:
            lines.append(
                "λ is large, so overlap is weak. The EIF contains inverse-propensity weights, which can increase variance even when cross-fitting is used."
            )
        return "\n\n".join(lines)

    return diagnostic_message, make_ci_plot, run_estimators


@app.cell(hide_code=True)
def _(
    lab_n,
    lab_overfit,
    lab_overlap,
    lab_propensity,
    lab_run_button,
    lab_seed,
    mo,
    run_estimators,
):
    mo.stop(not lab_run_button.value, mo.md("Press **Run DML/TMLE experiment** after selecting the four levers."))
    lab_df, lab_results, lab_diagnostic_table, lab_true_psi = run_estimators(
        n=lab_n.value,
        overlap_lambda=lab_overlap.value,
        kappa=lab_overfit.value,
        propensity_choice=lab_propensity.value,
        seed=lab_seed.value,
    )
    return lab_diagnostic_table, lab_results, lab_true_psi


@app.cell(hide_code=True)
def _(
    diagnostic_message,
    lab_diagnostic_table,
    lab_overfit,
    lab_overlap,
    lab_propensity,
    lab_results,
    lab_true_psi,
    make_ci_plot,
    mo,
):
    fig = make_ci_plot(lab_results, lab_true_psi)
    mo.vstack([
        mo.md("## Results"),
        mo.md(r"The dashed vertical line is the finite-sample truth, \(n^{-1}\sum_i\tau(W_i)\)."),
        fig,
        lab_results.round(3),
        mo.md("## What makes DML different from naive AIPW here?"),
        lab_diagnostic_table.round(4),
        mo.md("## Diagnostic interpretation"),
        mo.md(diagnostic_message(lab_results, lab_diagnostic_table, lab_overfit.value, lab_overlap.value, lab_propensity.value)),
    ])
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Student discussion prompts

    1. Set \(\kappa=1\) and **use the true propensity scores**. Why can the naïve AIPW estimator be biased even though it uses the correct propensity score? What happened to the in-sample residuals? What happened to the confidence intervals?
    2. How do the AIPW and DML compare for different \(\kappa\), low and high?
    3. **Switch from true to misspecified propensity scores**. Which estimators change? Why does the plug-in not change?
    4. With misspecified propensity scores, how do the estimators perform?
    5. Increase \(\lambda\). What happens to the confidence intervals? Relate this to the inverse-propensity terms in the influence function.
    6. In real data, the dashed oracle line is not available. Which diagnostics would you want to see to select one estimator?
    7. Feel free to try new configurations and to check the code and formulate questions.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Running this notebook

    From the directory containing this file:

    ```bash
    pip install marimo numpy pandas matplotlib
    marimo edit 4_dml_tmle_marimo.py
    ```

    To serve it as an app instead of opening the notebook editor:

    ```bash
    marimo run 4_dml_tmle_marimo.py
    ```
    """)
    return


if __name__ == "__main__":
    app.run()
